# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7d471794e373cc7f24a916694caf634e2f114b680e352d7c457710414319c467b0484f627f6e4016945b2ade4323dacad0220cc20118a6ab9bfb68f619154f8

test:
  secret_key_base: ffa78884cad3753b62122d648df1936d9b83f88f6b50791b8bd45a98f5cdb2faf85aafc8226349810d8eb7bf1f85b5119bff260729b412072ad939755793e62a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
